---
- name: Setup demo env
  hosts: localhost
  vars:
    limit_host_group: windows-servers #used for LTO Field Test drive - adjust if using Windows workshop
  tasks:
    - name: Add tower project
      tower_project:
        name: "Windows Admin Tasks"
        description: "Set of playbooks that showcase windows admin tasks"
        organization: "Demo"
        scm_type: git
        scm_update_on_launch: yes
        scm_url: https://github.com/corumj/ansible-windows-admin-tasks
        state: present
        tower_config_file: "~/.tower_cli.cfg"
        validate_certs: no

    - name: pause for a moment to let Tower clone the git repo
      pause:
        seconds: 20

    - name: Create server provisioning job template
      tower_job_template:
        name: "Provision Server"
        job_type: "check"
        inventory: "Physical Inventory"
        project: "Windows Admin Tasks"
        playbook: "provision_vmware_host.yml"
        credential: "SSH Server Credentials"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"

    - name: Create Windows Update job template
      tower_job_template:
        name: "Windows Updates"
        job_type: "run"
        inventory: "Physical Inventory"
        project: "Windows Admin Tasks"
        playbook: "windows_updates.yml"
        credential: "Windows Credentials"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'windows_update_survey.json') }}"

    - name: Create add to windows domain job template
      tower_job_template:
        name: "Add server to domain"
        job_type: "check"
        inventory: "Physical Inventory"
        project: "Windows Admin Tasks"
        playbook: "add_server_to_domain.yml"
        credential: "Windows Credentials"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"

    - name: Create IIS Basic Install template
      tower_job_template:
        name: "IIS Basic Install"
        job_type: "check"
        inventory: "Physical Inventory"
        project: "Windows Admin Tasks"
        playbook: "iis_basic.yml"
        credential: "Windows Credentials"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'iis_basic_survey.json') }}"

    - name: Create Install .NET 3.5 template
      tower_job_template:
        name: "Install .NET 3.5"
        job_type: "check"
        inventory: "Physical Inventory"
        project: "Windows Admin Tasks"
        playbook: "install_dot_net.yml"
        credential: "Windows Credentials"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"

    - name: Create Install OpenJDK w/ Chocolatey Template
      tower_job_template:
        name: "Install OpenJDK w/ Chocolatey"
        job_type: "run"
        inventory: "Physical Inventory"
        project: "Windows Admin Tasks"
        playbook: "install_openjdk.yml"
        credential: "Windows Credentials"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"

    - name: Create Install OpenJDK w/ MSI template
      tower_job_template:
        name: "Install OpenJDK w/ MSI"
        job_type: "run"
        inventory: "Physical Inventory"
        project: "Windows Admin Tasks"
        playbook: "install_openjdk_msi.yml"
        credential: "Windows Credentials"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"
