---
- name: Setup demo env
  hosts: localhost
  gather_facts: no
  vars:
    # This section should be uncommented if using LTO Field Test Drive
    # credentials: "Windows Credentials" # Windows Credentials for LTO, Workshop Credential otherwise
    # inventory: "Physical Inventory" # Physical Inventory if LTO, Workshop Inventory otherwise
    # organization: Demo # Demo if LTO, Default if Workshop
    # limit_host_group: windows-servers # windows-servers if LTO, windows if workshop
    # This section should be uncommented if using the Windows Workshop
    credentials: "Workshop Credential"
    inventory: "Workshop Inventory"
    organization: Default
    limit_host_group: windows
  tasks:
    - name: Add tower project
      tower_project:
        name: "Windows Admin Tasks"
        description: "Set of playbooks that showcase windows admin tasks"
        organization: "{{ organization }}"
        scm_type: git
        scm_update_on_launch: yes
        scm_url: https://github.com/corumj/ansible-windows-admin-tasks
        state: present
        tower_config_file: "~/.tower_cli.cfg"
        validate_certs: no

    - name: pause for a moment to let Tower clone the git repo
      pause:
        seconds: 20

    - name: Create server provisioning job template
      tower_job_template:
        name: "Provision Server"
        job_type: "check"
        inventory: "{{ inventory }}"
        project: "Windows Admin Tasks"
        playbook: "provision_vmware_host.yml"
        credential: "{{ credentials }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"

    - name: Create Windows Update job template
      tower_job_template:
        name: "Windows Updates"
        job_type: "run"
        inventory: "{{ inventory }}"
        project: "Windows Admin Tasks"
        playbook: "windows_updates.yml"
        credential: "{{ credentials }}"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'windows_update_survey.json') }}"

    - name: Create add to windows domain job template
      tower_job_template:
        name: "Add server to domain"
        job_type: "check"
        inventory: "{{ inventory }}"
        project: "Windows Admin Tasks"
        playbook: "add_server_to_domain.yml"
        credential: "{{ credentials }}"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"

    - name: Create IIS Basic Install template
      tower_job_template:
        name: "IIS Basic Install"
        job_type: "check"
        inventory: "{{ inventory }}"
        project: "Windows Admin Tasks"
        playbook: "iis_basic.yml"
        credential: "{{ credentials }}"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'iis_basic_survey.json') }}"

    - name: Create Install .NET 3.5 template
      tower_job_template:
        name: "Install .NET 3.5"
        job_type: "check"
        inventory: "{{ inventory }}"
        project: "Windows Admin Tasks"
        playbook: "install_dot_net.yml"
        credential: "{{ credentials }}"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"

    - name: Create Install OpenJDK w/ Chocolatey Template
      tower_job_template:
        name: "Install OpenJDK w/ Chocolatey"
        job_type: "run"
        inventory: "{{ inventory }}"
        project: "Windows Admin Tasks"
        playbook: "install_openjdk.yml"
        credential: "{{ credentials }}"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"

    - name: Create Install NodeJS w/ MSI template
      tower_job_template:
        name: "Install NodeJS w/ MSI"
        job_type: "run"
        inventory: "{{ inventory }}"
        project: "Windows Admin Tasks"
        playbook: "install_nodejs_msi.yml"
        credential: "{{ credentials }}"
        limit: "{{ limit_host_group }}"
        state: "present"
        tower_config_file: "~/.tower_cli.cfg"

    - name: Create the Demo Workflow
      tower_workflow_template:
        name: Windows Demo Workflow
        description: Demo Workflow Template
        organization: "{{ organization }}"
        schema: "{{ lookup('file', 'demo_workflow.yml') }}"