---
- name: Deploy demo front end
  hosts: tag_app_frontend 

  vars:
    protocol: http
    port: 8081
    backend_hostname: "{{ hostvars[groups['tag_app_backend'][0]]['public_dns_name'] }}"
  tasks:
    - name: ensure git is installed
      chocolatey.chocolatey.win_chocolatey:
        name: git
        state: present
      
    - name: create temp folder to checkout repo 
      ansible.windows.win_tempfile:
        state: directory
        suffix: build 
      register: temp_dir

    - name: checkout front end repo  
      ansible.windows.win_shell: |
        git --no-pager clone https://github.com/corumj/simple-address-book {{ temp_dir.path }}

    # - name: checkout front end repo 
    #   ansible.builtin.git:
    #     repo: 'https://github.com/corumj/simple-address-book'
    #     dest: "{{ temp_dir.path }}"

    - name: Remove unneccessary files 
      ansible.windows.win_file:
        path: "{{ temp_dir.path }}\\{{ item }}"
        state: absent 
      loop:
        - Containerfile
        - LICENSE
        - README.md 
        - entrypoint.sh 

    - name: overwrite config with template 
      ansible.windows.win_template:
        src: sab_config.json.j2 
        dest: "{{ temp_dir.path }}\\config.default.json"

    - name: Copy app to IIS directory 
      ansible.windows.win_copy:
        remote_src: yes 
        src: "{{ temp_dir.path }}/"
        dest: C:\Inetpub\wwwroot


      