---
- name: Grant rights to a domain account
  hosts: all
  tasks:
    - name: Grant domain account the SeServiceLogonRight user right needed to run as a service
      win_user_right:
        name: SeServiceLogonRight
        users:
          - DOMAIN\User
        action: add