---
- name: Remove the iis web service
  hosts: all
  tasks:
    - name: Stop iis service
      win_service:
        name: W3Svc
        state: stopped

    - name: Remove iis
      win_feature:
        name: Web-Server
        state: absent

