---
- name: Test that server is configured as expected
  hosts: all
  gather_facts: yes
  vars:
    iis_test_message: "Hello, world!"
  tasks:
    # - name: print hostvars
    #   debug:
    #     var: hostvars[inventory_hostname]

    - name: Check for 200 response from IIS 
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_ip_addresses'][0] }}"
      register: response 
      delegate_to: localhost
      

    - name: check content
      assert: 
        that:
          - response.content == "Hello, world!"
      ignore_errors: yes
