---
- name: Test that server is configured as expected
  hosts: all
  vars:
    iis_test_message: "Hello, world!"
    iis_url: "http://{{ ansible_default_ipv4.address }}"
  tasks:
    - name: Check for 200 response from IIS 
      ansible.builtin.uri:
        url: "{{ iis_url }}"
      register: response 

    - name: check content
      assert: 
        that:
          - response.content == "Hello, world!"
