---
- name: Test that server is configured as expected
  hosts: all
  gather_facts: yes
  vars:
    iis_test_message: "Hello, world!"
  tasks:
    - name: Check for 200 response from IIS 
      ansible.builtin.uri:
        url: "http://{{ ansible_all_ipv4_addresses[0] }}"
      register: response 

    - name: check content
      assert: 
        that:
          - response.content == "Hello, world!"
