---
- name: This is my Windows patching playbook
  hosts: all
  tasks:
    - name: Install Windows Updates
      win_updates:
        category_names: "{{ categories | default(omit) }}"
        reboot: '{{ reboot_server | default(yes) }}'